# 長庚資訊工程系 樣型識別 HW3

**All-ones or all-zeros tensors**

In [ ]:
import tensorflow as tf
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [ ]:
x[0]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
x[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [ ]:
y=[1,10]

In [ ]:
y[0]

1

In [ ]:
y[1]

10

In [ ]:
xv= tf.Variable(x)

In [ ]:
xv

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [ ]:
xv[0,0]=1000

TypeError: ignored

In [ ]:
xv[0,0].assign(1000)

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=float32, numpy=
array([[1000.],
       [   1.]], dtype=float32)>

In [ ]:
x = tf.zeros(shape=(2, 1))
print(x)

**Random tensors**

In [ ]:
x = tf.random.normal((10, 2), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[-0.30534193  0.50756663]
 [ 1.4019108  -0.8714041 ]
 [-0.6209944  -0.44227117]
 [-0.46680215  0.3048662 ]
 [ 1.1445593   0.67217255]
 [ 1.5166378  -1.3197571 ]
 [-1.4864608   0.4017857 ]
 [ 0.26023418 -0.22623922]
 [ 0.73226494  0.95248854]
 [-1.1024257   0.3854276 ]], shape=(10, 2), dtype=float32)


In [ ]:
x = tf.random.normal((3, 2, 2), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[[-0.70905393 -0.5882439 ]
  [ 0.46232405  0.50029737]]

 [[ 1.1039468   0.7175455 ]
  [ 0.37740415  1.3439815 ]]

 [[-1.9839758  -0.46178842]
  [-0.63732064  0.7589246 ]]], shape=(3, 2, 2), dtype=float32)


In [ ]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.67781544]
 [0.4663149 ]
 [0.5130912 ]], shape=(3, 1), dtype=float32)


In [ ]:
x = tf.random.normal((2, 3, 4, 5), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[[[ 1.1392342   0.10203981 -0.5483602  -0.85761696 -0.689661  ]
   [-0.7006561   0.14711888 -1.1455247   0.19616084  1.5512327 ]
   [ 0.3854424   0.3229125   1.2884238   0.6632706  -1.9696144 ]
   [-0.5665729   0.57692397 -0.24064924  0.27633375  1.56731   ]]

  [[-0.6097444  -0.83733356  0.31950065 -1.3635501   0.44559222]
   [ 0.9696624  -2.0253458   0.28242466  0.73629457  0.64435846]
   [-2.0873623  -0.24354914 -1.9681566  -2.5649405  -0.7662077 ]
   [-1.4700251   2.1657858   0.90859485 -0.7718347  -0.5310282 ]]

  [[-0.03867773  0.76757145  0.07378371  0.31334126 -0.5320235 ]
   [ 0.85730875 -0.3859333  -0.6212135   2.084796    0.7115182 ]
   [-0.33692774 -0.5376214   0.62941885 -1.3240606  -0.6258273 ]
   [-0.63809484  0.56132126  1.2074109   1.3601882   2.6905727 ]]]


 [[[-1.9878974   0.9439776  -0.52718323 -0.02262278 -2.1834857 ]
   [ 0.5289054  -0.43845552  0.0600971  -0.97907877 -0.58663625]
   [-2.40867    -0.4920515  -0.53552467 -2.7793975   0.22248979]
   [ 1

**NumPy arrays are assignable**

In [ ]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

**Creating a TensorFlow variable**

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

**Assigning a value to a TensorFlow variable**

In [ ]:
v.assign(tf.ones((3, 1)))

**Assigning a value to a subset of a TensorFlow variable**

In [ ]:
v[0, 0].assign(3.)

**Using `assign_add`**

In [ ]:
v.assign_add(tf.ones((3, 1)))

#### Tensor operations: Doing math in TensorFlow

**A few basic math operations**

In [ ]:
a = tf.ones((2, 2))*100
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100., 100.],
       [100., 100.]], dtype=float32)>

In [ ]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10000., 10000.],
       [10000., 10000.]], dtype=float32)>

In [ ]:
c = tf.sqrt(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float32)>

In [ ]:
d = b + c
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10010., 10010.],
       [10010., 10010.]], dtype=float32)>

In [ ]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d

#### A second look at the GradientTape API

**Using the `GradientTape`**

In [ ]:
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
input_var, gradient

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [ ]:
x = tf.Variable(3.)
with tf.GradientTape() as t:
  y= x**2
dy_dx= t.gradient(y,x)
x,y,dy_dx


(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [ ]:
def f(x):
  y= x**3+ x**2+ x+ 1
  return y

x = tf.Variable(10.)
with tf.GradientTape() as t:
  y= f(x)
dy_dx= t.gradient(y,x)
x,y,dy_dx

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1111.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=321.0>)

**Using `GradientTape` with constant tensor inputs**

In [ ]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
   tape.watch(input_const)
   result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

**Using nested gradient tapes to compute second-order gradients**

In [ ]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position =  4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

#### An end-to-end example: A linear classifier in pure TensorFlow

**Generating two classes of random points in a 2D plane**

In [ ]:
num_samples_per_class = 1000
negative_samples = np.random.multivariate_normal(
    mean=[0, 3],
    cov=[[1, 0.5],[0.5, 1]],
    size=num_samples_per_class)
positive_samples = np.random.multivariate_normal(
    mean=[3, 0],
    cov=[[1, 0.5],[0.5, 1]],
    size=num_samples_per_class)

**Stacking the two classes into an array with shape (2000, 2)**

In [ ]:
inputs = np.vstack((negative_samples, positive_samples)).astype(np.float32)

**Generating the corresponding targets (0 and 1)**

In [ ]:
targets = np.vstack((np.zeros((num_samples_per_class, 1), dtype="float32"),
                     np.ones((num_samples_per_class, 1), dtype="float32")))

**Plotting the two point classes**

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(inputs[:, 0], inputs[:, 1], c=targets[:, 0])
plt.show()

**Creating the linear classifier variables**

In [ ]:
input_dim = 2
output_dim = 1
W = tf.Variable(initial_value=tf.random.uniform(shape=(input_dim, output_dim)))
b = tf.Variable(initial_value=tf.zeros(shape=(output_dim,)))

**The forward pass function**

In [ ]:
def model(inputs):
    return tf.matmul(inputs, W) + b

**The mean squared error loss function**

In [ ]:
def square_loss(targets, predictions):
    per_sample_losses = tf.square(targets - predictions)
    return tf.reduce_mean(per_sample_losses)

**The training step function**

In [ ]:
learning_rate = 0.1

def training_step(inputs, targets):
    with tf.GradientTape() as tape:
        predictions = model(inputs)
        loss = square_loss(targets, predictions)
    grad_loss_wrt_W, grad_loss_wrt_b = tape.gradient(loss, [W, b])
    W.assign_sub(grad_loss_wrt_W * learning_rate)
    b.assign_sub(grad_loss_wrt_b * learning_rate)
    return loss

**The batch training loop**

In [ ]:
for step in range(40):
    loss = training_step(inputs, targets)
    print(f"Loss at step {step}: {loss:.4f}")

In [ ]:
predictions = model(inputs)
plt.scatter(inputs[:, 0], inputs[:, 1], c=predictions[:, 0] > 0.5)
plt.show()

In [ ]:
x = np.linspace(-1, 4, 100)
y = - W[0] /  W[1] * x + (0.5 - b) / W[1]
plt.plot(x, y, "-r")
plt.scatter(inputs[:, 0], inputs[:, 1], c=predictions[:, 0] > 0.5)

## Anatomy of a neural network: Understanding core Keras APIs

### Layers: The building blocks of deep learning

#### The base Layer class in Keras

**A `Dense` layer implemented as a `Layer` subclass**

In [ ]:
from tensorflow import keras

class SimpleDense(keras.layers.Layer):

    def __init__(self, units, activation=None):
        super().__init__()
        self.units = units
        self.activation = activation

    def build(self, input_shape):
        input_dim = input_shape[-1]
        self.W = self.add_weight(shape=(input_dim, self.units),
                                 initializer="random_normal")
        self.b = self.add_weight(shape=(self.units,),
                                 initializer="zeros")

    def call(self, inputs):
        y = tf.matmul(inputs, self.W) + self.b
        if self.activation is not None:
            y = self.activation(y)
        return y

In [ ]:
my_dense = SimpleDense(units=32, activation=tf.nn.relu)
input_tensor = tf.ones(shape=(2, 784))
output_tensor = my_dense(input_tensor)
print(output_tensor.shape)

#### Automatic shape inference: Building layers on the fly

In [ ]:
from tensorflow.keras import layers
layer = layers.Dense(32, activation="relu")

In [ ]:
from tensorflow.keras import models
from tensorflow.keras import layers
model = models.Sequential([
    layers.Dense(32, activation="relu"),
    layers.Dense(32)
])

In [ ]:
model = keras.Sequential([
    SimpleDense(32, activation="relu"),
    SimpleDense(64, activation="relu"),
    SimpleDense(32, activation="relu"),
    SimpleDense(10, activation="softmax")
])

### From layers to models

### The "compile" step: Configuring the learning process

In [ ]:
model = keras.Sequential([keras.layers.Dense(1)])
model.compile(optimizer="rmsprop",
              loss="mean_squared_error",
              metrics=["accuracy"])

In [ ]:
model.compile(optimizer=keras.optimizers.RMSprop(),
              loss=keras.losses.MeanSquaredError(),
              metrics=[keras.metrics.BinaryAccuracy()])

### Picking a loss function

### Understanding the fit() method

**Calling `fit()` with NumPy data**

In [ ]:
history = model.fit(
    inputs,
    targets,
    epochs=5,
    batch_size=128
)

In [ ]:
history.history

### Monitoring loss and metrics on validation data

**Using the `validation_data` argument**

In [ ]:
model = keras.Sequential([keras.layers.Dense(1)])
model.compile(optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
              loss=keras.losses.MeanSquaredError(),
              metrics=[keras.metrics.BinaryAccuracy()])

indices_permutation = np.random.permutation(len(inputs))
shuffled_inputs = inputs[indices_permutation]
shuffled_targets = targets[indices_permutation]

num_validation_samples = int(0.3 * len(inputs))
val_inputs = shuffled_inputs[:num_validation_samples]
val_targets = shuffled_targets[:num_validation_samples]
training_inputs = shuffled_inputs[num_validation_samples:]
training_targets = shuffled_targets[num_validation_samples:]
model.fit(
    training_inputs,
    training_targets,
    epochs=5,
    batch_size=16,
    validation_data=(val_inputs, val_targets)
)

### Inference: Using a model after training

In [ ]:
predictions = model.predict(val_inputs, batch_size=128)
print(predictions[:10])

## Summary